name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Deploying to $SERVER_HOST"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -p 7082 $SERVER_USER@$SERVER_HOST << EOF
            cd ~/promama-infra
            docker-compose up -d --build
          EOF
        shell: /usr/bin/bash -e {0}
