name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to $SERVER_HOST"
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key -p 7082 $SERVER_USER@$SERVER_HOST << EOF
            cd ~/promama-infra
            docker-compose up -d --build
          EOF

          rm /tmp/ssh_key
        shell: /usr/bin/bash -e {0}
